### ISSUE TITLE
[BUG] A tag bug

### ISSUE THREAD

**Issue by Lazyevilsquid** [kyechan99/kyechan99.github.io#7]
**Screenshots**
![image](https://user-images.githubusercontent.com/19345932/96363829-909b3700-1171-11eb-8eb8-809e74282ca6.png)

* /lib/2020/05/22/jekyll-custom-4.html 에
```<a href="/lib/2020/05/22/jekyll-custom-3">Jekyll Custom 블로그 만들기 - 3</a>``` 를 
```<a href="/lib/2020/05/19/jekyll-custom-3">Jekyll Custom 블로그 만들기 - 3</a>``` 로 바꿔주세요

**Comment by kyechan99** [comment]
ㅎㅎㅎ 감사합니다
